apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: hello-world
  name: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hello-world
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/hello-nginx-default: "true"
        io.kompose.service: hello-world
    spec:
      containers:
        - image: jose10000/hello-world:v1.1
          name: hello-world
          ports:
            - containerPort: 80
              hostPort: 8090
              protocol: TCP
      restartPolicy: Always
