FROM python:3.8-slim-buster                 # Base image, in this case, python 3.8 an is pulled from docker hub, it is an images repository,(https://hub.docker.com/_/python)

WORKDIR /app                                # Set the working directory to /app

COPY requirements.txt requirements.txt      # Copy the requirements.txt file to the working directory.
RUN pip3 install -r requirements.txt        # Install the dependencies

COPY . .                                    # Copy the current directory contents into the container at /app, the current directory is the directory where the Dockerfile is located

CMD [ "python3", "-m" , "flask", "run", "--host=10.0.0.1"]  # Run the command when the container starts

